# Generated by Django 6.0 on 2025-12-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='greeting',
            name='when',
        ),
        migrations.AddField(
            model_name='greeting',
            name='message',
            field=models.CharField(default='Hello', max_length=255),
        ),
    ]
