# Generated by Django 6.0 on 2026-01-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_visit_remove_greeting_when_greeting_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
